# Generated by Django 2.0.5 on 2018-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_img', models.CharField(default='0b444f3a9032.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ListArticle',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=100)),
                ('list_img', models.CharField(default='7bee776a-73e0-472b-a3e1-20c53bd6aed6.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urlid', models.CharField(default='1_1', max_length=100)),
                ('author', models.CharField(default='佚名', max_length=100)),
                ('title', models.CharField(default='标题', max_length=200)),
                ('keyword', models.CharField(default='关键词', max_length=200)),
                ('description', models.TextField(default='描述')),
                ('create_time', models.DateTimeField(verbose_name='date published')),
                ('quantity', models.IntegerField(default=0)),
                ('read', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('img', models.TextField(default='1.jpg,2.jpg')),
                ('video', models.TextField(default='1.mp4')),
                ('context', models.TextField(default='文章内容')),
                ('url', models.CharField(default='url', max_length=200)),
                ('tips', models.CharField(choices=[('list_shehui', '社会热点'), ('list_dushu', '读书'), ('list_renwen', '人文社科'), ('list_ziran', '自然科普'), ('list_gushi', '故事'), ('list_shouhui', '手绘'), ('list_luxing', '旅行。在路上')], default='list_gushi', max_length=100)),
                ('source', models.CharField(choices=[('S1', '/47.90.63.143/news/饮食男女/'), ('S2', '/47.90.63.143/news/娱乐/'), ('S3', '/47.90.63.143/news/果籽/')], default='source one', max_length=200)),
            ],
        ),
    ]
