# Generated by Django 2.0.5 on 2018-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='urlid',
            field=models.CharField(default='1_1', max_length=100, unique=True),
        ),
    ]
