# Generated by Django 2.0.5 on 2018-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSModel', '0003_auto_20180801_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='video',
            new_name='videoUrls',
        ),
    ]
