# Generated by Django 2.0.5 on 2018-08-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSModel', '0005_listarticle_list_ch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='_id',
            new_name='re_id',
        ),
    ]
